### ISSUE TITLE
CardanoDBSync leaking connections...

### ISSUE THREAD

**Issue by mgajda** [IntersectMBO/cardano-db-sync#1373]
**OS**
Your OS: Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): input-output-hk/cardano-db-sync:13.1.0.3 (docker image)
PostgreSQL version: postgres:11.5-alpine (docker image)

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: IOHK docker image

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): K8S (docker)

**Additional context**

We are interested in making CardanoDBSync run reliably for as long as possible.
There is only one client app, and we made sure it does not make more than few connections.

**Problem Report**

CardanoDBSync takes all the connection capacity of the Postgres server by trying 100 connections simultaneously. Terminating CardanoDBSync fixes the problem.

**Comment by erikd** [comment]
Reproducer please.

**Comment by kderme** [comment]
Indeed it's possible that DBSync can leak connections. Some detailed technical explanation follows:

This is most probably the result of https://github.com/input-output-hk/cardano-db-sync/pull/1155/commits/fbae4ad78c204d10201cdc43da98987a554a10fd, which was a fix for https://github.com/input-output-hk/cardano-db-sync/issues/1135. This fix was rather a workaround, as the actual problem comes from the upstream postgres bindings library https://github.com/lpsmith/postgresql-simple/issues/200 which hasn't been fully solved.

To explain the problem more, if there is an exception at a specific moment (eg because the connection with the node was lost or the node has restarted), the postgres connection can enter an undefined state where it cannot be used or even closed. So we just reopen a new connection, ignoring the old one, which leaks.

The solution is to find exactly what happens with this connection which was interrupted and find a way to close it. Or rather catch the network exception earlier, so it doesn't affect the postgres connection.

**Comment by kderme** [comment]
Could you provide some more information about how you run DBSync and how fast or how ofter it reaches a big number of connections? Do you see any connection errors with the node?

**Comment by mgajda** [comment]
We run DBSync `13.1` on `mainnet` in a separate container for about 10 days before it happens.
So for us it happens each time.

There are only few clients, one with `LISTEN` on the `blocks` table.
Beside the application, the clients are PG node exporter for prometheus and internal jobs (WAL, autovacuum).

**Comment by mgajda** [comment]
> Reproducer please.

I am sorry, but this is a type of error that is hard to reproduce without waiting 10 days.
The cause for disconnects is unknown, and probably another bug.
