### ISSUE TITLE
Question: --consumed-tx-out and Snapshots

### ISSUE THREAD

**Issue by AlanVerbner** [IntersectMBO/cardano-db-sync#1616]
# Description

Hi, I'm writing because it wasn't able to find it on the documentation. I'm wondering if [--consumed-tx-out](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/configuration.md#--consumed-tx-out) flag is compatible with the snapshot restoring (I would guess there is a schema difference because the new column).

Thanks!

**Comment by kderme** [comment]
Snapshots use the default db-sync flavour, which doesn't enable the `--consumed-tx-out` flag. You could restore the snapshot and then enable it, but this migration is very slow. It will create the `tx_out.consumed_by_tx_id` column and for each `tx_in` entry it will update exactly one `tx_out.consumed_by_tx_id` field. The fact that there are so many updates and that postgres is not really optimised for updates makes this process very slow. Also note this flag eventually drops all `tx_in` entries, since they become redundant.

**Comment by AlanVerbner** [comment]
Hi @kderme, thanks a lot for your answer. 

Maybe different snapshots for different setups could be uploaded in the future, does that make sense? I mean, running `cardano-db-sync` on each mode and then creating a snapshot accordingly.

In any case I'm closing this issue as you provided the answer I neded.

Thanks again 🙌
