### ISSUE TITLE
Unable to query live stake only active stake

### ISSUE THREAD

**Issue by 3cogito** [IntersectMBO/cardano-db-sync#599]
There is no easy way to query live stake, only active stake. Add a live stake table or stored proceedure.

**Comment by failfectionist** [comment]
Unless I'm misunderstanding your question, all stake (e.g. all epochs) is in the database under the epoch_stake table. Why would you need anything else?

**Comment by erikd** [comment]
My understanding is that "live stake" is the current stake distribution at the current tip of the chain. As such this distribution changes nearly every time a new block containing transactions arrives. There are currently over 300,000 registered stake addresses, this is a **LARGE** chunk of data. 

Obviously querying ledger state for the current live stake on every new block and then inserting that into the database is a huge computational load. Currently inserting the stake mapping at the end of each epoch takes over 5 minutes, so that is out of the question.

As for providing a view or something provides live stake is probably possible, but is a non-trivial task that has a lower priority that a bunch of other things.

**Comment by erikd** [comment]
Acitve stake is problematic in that it is so different from other things store in the database. Most tables (`epoch` being the only exception) are append only, in that data once written is never modified or deleted.

However, "active stake" is by definition transitory. There is zero benefit on keeping past "active stake" sets so they will constant be deleted and replaced. Also, since this is a *LARGE* chunk of data, it could easily interfere with normal `db-sync` operations.

> How does Daedalus calculate this, can that query simply be reused?

The query is not the problem, its completely trivial to get the data. The problem is loading the data into PostgreSQL. I actually think an SQL query might be a better way to do this.

**Comment by mik1893** [comment]
I have created a query to monitor live stake, happy to share it here. 

`
CREATE VIEW live_stake AS 
-- this query will always pick latest stake delegation for an address allowing to query for live stake
WITH current_delegation AS (
 	SELECT DISTINCT ON (delegation.addr_id) delegation.addr_id,
   delegation.pool_hash_id
   FROM delegation
   ORDER BY delegation.addr_id, delegation.slot_no DESC, delegation.pool_hash_id 
)

SELECT stake_address.view as stake_addr, current_delegation.pool_hash_id as pool_id, CAST(SUM(tx_out.value)/1000000 AS BIGINT) AS stake_amount
FROM tx_out 
	LEFT JOIN tx_in ON tx_out.tx_id = tx_in.tx_out_id AND tx_out.index::smallint = tx_in.tx_out_index::smallint
	LEFT JOIN current_delegation ON current_delegation.addr_id = tx_out.stake_address_id 
	LEFT JOIN stake_address ON stake_address.id = current_delegation.addr_id 

WHERE 
	tx_in.tx_in_id IS NULL 
	
GROUP BY stake_address.view, current_delegation.pool_hash_id
ORDER BY 2 DESC
 `

You can then query live stake for a specific pool using the pool_hash id  (example for my pool, ADATA, this 12171)

**Comment by cyber-russ** [comment]
Thanks very much for sharing. This works well.
The numbers are close to those produced by adapools.org and pooltool.io (both of which vary from each other) but approximately 1-2% lower for stake amounts closer to saturation:

for example (ADAvault):
SELECT SUM(stake_amount) from live_stake where pool_hash_id = 8675;

Any thoughts why they may all vary?

**Comment by mik1893** [comment]
i think i might be missing a piece of the join. Will check this out and find it :)

**Comment by cyber-russ** [comment]
> i think i might be missing a piece of the join. Will check this out and find it :)

Thanks a lot, would be great to get this running accurately

**Comment by mesudip** [comment]
This how you can query the balances of a stake address. and all the unspent utxos.

```
select utxo.value amount , utxo.address,encode(tx.hash,'hex') tx, utxo.index tx_index
from (tx_out  utxo
    join tx on  utxo.tx_id = tx.id)
         left join tx_in txo  on txo.tx_out_id= tx.id and txo.tx_out_index = utxo.index
where stake_address_id = (
    select id
    from stake_address
    where view = 'stake1uy5pzc9fvy58c375y4emkdyz8a5qmlj2fadf5rzxew4jzesdm9txz'
) and txo.id is null ;
```

if you want only the total amount, replace the select clause with  `select coalesce(sum(utxo.value),0) amount`.

The result will be accurate if db-sync is synced. Some sites might show higher amount than this, It is because they add rewards that are not withdrawn to this value.

**Comment by Cmdv** [comment]
Based on the provided information, it seems that the issue has been addressed. We're closing this issue now. If you have any more concerns or if the problem reappears, please let us know by reopening this issue. We appreciate your help!
